name: Sync Main with Feature Branch

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Git login
        run: git config --global user.email "saiseshu1919@gmail.com"
             git config --global user.name "saiseshu1919"
             
      - name: Checkout main branch
        run: git checkout main

      - name: Pull latest changes
        run: git pull

      - name: Checkout feature branch
        run: git checkout feature-branch

      #- name: Rebase feature branch with main
      #  run: git rebase main

      - name: Push changes to feature branch
        run: git push origin feature-branch
