name: Sync main to master

on:
  push:
    branches:
      - main

jobs:
  sync-to-master:
    name: sync-to-master
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Synchronize main and feature branches
      run: |
        git checkout feature-branch
        git merge main --no-edit
        git push origin feature-branch
