name: Sync Feature Branch with Main

on:
  push:
    branches:
      - main

jobs:
  sync-feature-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Sync with Main
      run: |
        git checkout -B feature-branch
        git pull origin main
        git push --force origin feature-branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
